# Generated by Django 2.2.23 on 2021-09-23 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=2, help_text='GPA of the applicant', max_digits=3)),
                ('major', models.CharField(help_text='Major of the applicant.', max_length=255, verbose_name='Major')),
                ('university', models.CharField(help_text='University of the applicant.', max_length=255, verbose_name='University')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewerName', models.CharField(help_text='Name of the reviewer.', max_length=255, verbose_name='Name')),
                ('leadership', models.PositiveSmallIntegerField(help_text='Leadership rating of candidate.', verbose_name='Leadership')),
                ('extracurriculars', models.PositiveSmallIntegerField(help_text='Extracurriculars rating of candidate.', verbose_name='Extracurriculars')),
                ('recLetters', models.PositiveSmallIntegerField(help_text='RecLetters rating of candidate.', verbose_name='RecLetters')),
                ('interview', models.PositiveSmallIntegerField(help_text='Interview rating of candidate.', verbose_name='Interview')),
                ('essay', models.PositiveSmallIntegerField(help_text='Essay rating of candidate.', verbose_name='Essay')),
                ('candidate', models.ForeignKey(help_text='Target candidate.', on_delete=django.db.models.deletion.CASCADE, to='reviews.Candidate', verbose_name='Candidate')),
            ],
        ),
    ]
