# Generated by Django 2.2.23 on 2021-09-25 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(default='', help_text='Email of Candidate', max_length=255, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='firstName',
            field=models.CharField(default='', help_text='First Name of Candidate', max_length=255, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='lastName',
            field=models.CharField(default='', help_text='Last Name of Candidate', max_length=255, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone Number of Candidate', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
