# Generated by Django 2.2.23 on 2021-09-25 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210925_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewform',
            name='leadership',
            field=models.IntegerField(help_text='Leadership rating of candidate.', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Leadership'),
        ),
    ]
