# Generated by Django 2.2.23 on 2021-09-25 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210925_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewform',
            name='leadership',
            field=models.PositiveIntegerField(help_text='Leadership rating of candidate.', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Leadership'),
        ),
    ]
