# Generated by Django 2.2.23 on 2021-09-28 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20210926_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewform',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
